- name: Set up LAN CA with OpenSSL using community.crypto
  hosts: ca_server
  become: yes
  collections:
    - community.crypto
  tasks:
    - name: Install OpenSSL
      dnf:
        name: openssl
        state: present
    - name: Create CA directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: "{{ '0700' if 'private' in item else '0755' }}"
      loop:
        - /etc/pki/lan-ca
        - /etc/pki/lan-ca/certs
        - /etc/pki/lan-ca/private
        - /etc/pki/lan-ca/crl
        - /etc/pki/lan-ca/newcerts
    - name: Create index and serial files
      copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { dest: /etc/pki/lan-ca/index.txt, content: '' }
        - { dest: /etc/pki/lan-ca/serial, content: '1000\n' }
    - name: Generate CA private key (ECDSA)
      openssl_privatekey:
        path: /etc/pki/lan-ca/private/ca-key.pem
        type: ECC
        curve: secp384r1  # Strong curve, widely supported
        mode: '0400'
        state: present
    - name: Ensure CSR directory exists
      file:
        path: /etc/pki/tls/csrs
        state: directory
        mode: '0755'
      vars:
        csr_path: /etc/pki/tls/csrs
    - name: Generate CA CSR with subject and extensions
      community.crypto.openssl_csr:
        path: /etc/pki/tls/csrs/ca-csr.pem
        privatekey_path: /etc/pki/lan-ca/private/ca-key.pem
        common_name: "Smith LAN CA"
        subject:
          C: US
          ST: California
          L: SantaBarbara
          O: Home LAN
        basic_constraints:
          - CA:TRUE
          - pathlen:1
        basic_constraints_critical: true
        crl_distribution_points:
          full_name: 
            - 'http://certauthority.home.arpa/crl/lan-ca.crl'
        key_usage:
          - certificateSign
          - cRLSign
        key_usage_critical: true
        extended_key_usage:
          - codeSigning
        mode: '0600'
        state: present
    - name: Generate CA certificate
      community.crypto.x509_certificate:
        path: /etc/pki/lan-ca/certs/ca-cert.pem
        privatekey_path: /etc/pki/lan-ca/private/ca-key.pem
        csr_path: /etc/pki/tls/csrs/ca-csr.pem
        provider: selfsigned
        selfsigned_not_after: "+3650d"
        selfsigned_digest: sha256
        mode: '0644'
        state: present
    - name: Generate initial CRL
      x509_crl:
        path: /etc/pki/lan-ca/crl/lan-ca.crl
        privatekey_path: /etc/pki/lan-ca/private/ca-key.pem
        issuer:
          C: US
          ST: California
          L: SantaBarbara
          O: Home LAN
          CN: Smith LAN CA
        last_update: "+0d"
        next_update: "+365d"
