- name: Distribute CA certificate to all hosts
  hosts: all
  become: yes
  tasks:
    - name: Include Fedora variables
      include_vars:
        file: vars/fedora.yml
      when: ansible_distribution == "Fedora"

    - name: Include Debian variables
      include_vars:
        file: vars/debian.yml
      when: ansible_os_family == "Debian"

    - name: Include Home Assistant variable
      include_vars:
        file: vars/haos.yml
      when: ansible_distribution == "Alpine"

  
    - name: Copy CA certificate to hosts
      ansible.builtin.copy:
        src: /etc/pki/tls/certs/CA_cert.pem
        dest: "{{ ca_path }}/CA_cert.pem"
        owner: root
        group: root
        mode: '0644'

    - name: Update CA trust on Fedora
      ansible.builtin.command:
        cmd: update-ca-trust
      changed_when: true
      when: "'fedora' in group_names"

    - name: Update CA certificates on Debian
      ansible.builtin.command:
        cmd: update-ca-certificates
      changed_when: true
      when: "'debian' in group_names"
